tunnel: 3663beb6-957e-4620-99bd-65ac5b9187c1
credentials-file: /etc/cloudflared/creds.json

ingress:
  - hostname: label.montedelavilla.org
    service: http://label-studio:8080
  - service: http_status:404

